// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: dta.proto

package dta

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ExploreCommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectID  string `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	CommitHash string `protobuf:"bytes,2,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
}

func (x *ExploreCommitRequest) Reset() {
	*x = ExploreCommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExploreCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploreCommitRequest) ProtoMessage() {}

func (x *ExploreCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploreCommitRequest.ProtoReflect.Descriptor instead.
func (*ExploreCommitRequest) Descriptor() ([]byte, []int) {
	return file_dta_proto_rawDescGZIP(), []int{0}
}

func (x *ExploreCommitRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *ExploreCommitRequest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

type ExploreCommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExploreCommitResponse) Reset() {
	*x = ExploreCommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExploreCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploreCommitResponse) ProtoMessage() {}

func (x *ExploreCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploreCommitResponse.ProtoReflect.Descriptor instead.
func (*ExploreCommitResponse) Descriptor() ([]byte, []int) {
	return file_dta_proto_rawDescGZIP(), []int{1}
}

var File_dta_proto protoreflect.FileDescriptor

var file_dta_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x14, 0x45,
	0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x17, 0x0a, 0x15, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x50, 0x0a, 0x0e, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0d,
	0x45, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x15, 0x2e,
	0x45, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09,
	0x2e, 0x2f, 0x64, 0x74, 0x61, 0x3b, 0x64, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dta_proto_rawDescOnce sync.Once
	file_dta_proto_rawDescData = file_dta_proto_rawDesc
)

func file_dta_proto_rawDescGZIP() []byte {
	file_dta_proto_rawDescOnce.Do(func() {
		file_dta_proto_rawDescData = protoimpl.X.CompressGZIP(file_dta_proto_rawDescData)
	})
	return file_dta_proto_rawDescData
}

var file_dta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dta_proto_goTypes = []interface{}{
	(*ExploreCommitRequest)(nil),  // 0: ExploreCommitRequest
	(*ExploreCommitResponse)(nil), // 1: ExploreCommitResponse
}
var file_dta_proto_depIdxs = []int32{
	0, // 0: CommitExplorer.ExploreCommit:input_type -> ExploreCommitRequest
	1, // 1: CommitExplorer.ExploreCommit:output_type -> ExploreCommitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dta_proto_init() }
func file_dta_proto_init() {
	if File_dta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExploreCommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExploreCommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dta_proto_goTypes,
		DependencyIndexes: file_dta_proto_depIdxs,
		MessageInfos:      file_dta_proto_msgTypes,
	}.Build()
	File_dta_proto = out.File
	file_dta_proto_rawDesc = nil
	file_dta_proto_goTypes = nil
	file_dta_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommitExplorerClient is the client API for CommitExplorer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommitExplorerClient interface {
	ExploreCommit(ctx context.Context, in *ExploreCommitRequest, opts ...grpc.CallOption) (*ExploreCommitResponse, error)
}

type commitExplorerClient struct {
	cc grpc.ClientConnInterface
}

func NewCommitExplorerClient(cc grpc.ClientConnInterface) CommitExplorerClient {
	return &commitExplorerClient{cc}
}

func (c *commitExplorerClient) ExploreCommit(ctx context.Context, in *ExploreCommitRequest, opts ...grpc.CallOption) (*ExploreCommitResponse, error) {
	out := new(ExploreCommitResponse)
	err := c.cc.Invoke(ctx, "/CommitExplorer/ExploreCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommitExplorerServer is the server API for CommitExplorer service.
type CommitExplorerServer interface {
	ExploreCommit(context.Context, *ExploreCommitRequest) (*ExploreCommitResponse, error)
}

// UnimplementedCommitExplorerServer can be embedded to have forward compatible implementations.
type UnimplementedCommitExplorerServer struct {
}

func (*UnimplementedCommitExplorerServer) ExploreCommit(context.Context, *ExploreCommitRequest) (*ExploreCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExploreCommit not implemented")
}

func RegisterCommitExplorerServer(s *grpc.Server, srv CommitExplorerServer) {
	s.RegisterService(&_CommitExplorer_serviceDesc, srv)
}

func _CommitExplorer_ExploreCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExploreCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitExplorerServer).ExploreCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CommitExplorer/ExploreCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitExplorerServer).ExploreCommit(ctx, req.(*ExploreCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommitExplorer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CommitExplorer",
	HandlerType: (*CommitExplorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExploreCommit",
			Handler:    _CommitExplorer_ExploreCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dta.proto",
}
